{% set version = "0.6" %}

package:
  name: suds-jurko
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/suds-jurko/suds-jurko-{{ version }}.tar.bz2
  sha256: 29edb72fd21e3044093d86f33c66cf847c5aaab26d64cb90e69e528ef014e57f
  patches:
    - 0001-Exclude-tests-from-installation.patch

build:
  number: 1004
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - suds
    - suds.bindings
    - suds.mx
    - suds.sax
    - suds.transport
    - suds.umx
    - suds.xsd

about:
  home: http://bitbucket.org/jurko/suds
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: "Lightweight SOAP client (Jurko's fork)."

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan
